language: python

python:
  - 3.5

os:
  - linux

sudo: false

install: pip install -r scripts/requirements.txt
script:
 - python test/workout.py
 - pyflakes .
 - python test/are_files_linted.py
 - python test/validate.py

after_script:
 - pip install pep8
 - pep8 .

notifications:
  email:
    recipients:
      - eric@konklone.com
      - tauberer@govtrack.us
    on_success: change
    on_failure: change
